"""
Build or clean the OpenMDAO documentation.

Usage (from openmdao/docs/):
    python build_docs.py build             # full build
    python build_docs.py build --no-exec   # skip notebook execution
    python build_docs.py build --fast      # parallel Sphinx, no warnings-as-errors
    python build_docs.py clean             # remove all generated files

Output: _executed_book/_build/html/index.html
"""
import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent


def _banner(msg):
    bar = '=' * 61
    print(f'\n{bar}')
    print(msg)
    print(bar, flush=True)


def cmd_clean(args):
    """Remove all files generated by the build."""
    for path in [HERE / '_executed_book', HERE / 'openmdao_book' / '_srcdocs']:
        if path.exists():
            _banner(f'Removing {path.relative_to(HERE)}')
            shutil.rmtree(path)
    print('\nDone.')


def cmd_build(args):
    """Run the full documentation build pipeline."""
    os.environ.setdefault('PYDEVD_DISABLE_FILE_VALIDATION', '1')
    os.environ.setdefault('OMPI_MCA_rmaps_base_oversubscribe', '1')
    os.environ.setdefault('PRTE_MCA_rmaps_default_mapping_policy', ':oversubscribe')

    os.chdir(HERE)

    _banner('Disable SNOPT cells')
    subprocess.run(
        [sys.executable, 'openmdao_book/other/disable_snopt_cells.py'], check=True)

    _banner('Build source docs (API reference)')
    subprocess.run([sys.executable, 'build_source_docs.py'], check=True)

    _banner('Copy source tree to _executed_book/')
    src = HERE / 'openmdao_book'
    dst = HERE / '_executed_book'
    # Copy all non-notebook supporting files (data files, scripts, static assets)
    # so they are present alongside the notebooks when papermill executes them.
    # Notebooks are NOT copied here — papermill writes them directly to _executed_book/,
    # which allows execute_notebooks.py to use timestamps to skip up-to-date notebooks.
    for item in src.rglob('*'):
        if not item.is_file():
            continue
        rel = item.relative_to(src)
        if '_build' in rel.parts or '.ipynb_checkpoints' in rel.parts:
            continue
        if item.suffix == '.ipynb':
            continue
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)

    if not args.no_exec:
        _banner('Execute notebooks')
        exec_cmd = [sys.executable, 'execute_notebooks.py']
        if args.workers is not None:
            exec_cmd += ['--workers', str(args.workers)]
        if args.no_serial:
            exec_cmd += ['--no-serial']
        if args.no_mpi:
            exec_cmd += ['--no-mpi']
        subprocess.run(exec_cmd, check=True)
    else:
        print('Skipping notebook execution (--no-exec)')

    if args.no_serial or args.no_mpi:
        print('\nSkipping Sphinx build (partial notebook execution).')
        return

    _banner('Build HTML with Sphinx')
    sphinx_cmd = ['sphinx-build', '-b', 'html', '--keep-going']
    if args.fast:
        sphinx_cmd += ['-j', 'auto']
    else:
        sphinx_cmd += ['-W']
    sphinx_cmd += [str(dst), str(dst / '_build' / 'html')]
    subprocess.run(sphinx_cmd, check=True)

    _banner('Copy build artifacts')
    subprocess.run([sys.executable, 'copy_build_artifacts.py'], check=True)

    print('\nDone. Docs available at: openmdao/docs/_executed_book/_build/html/index.html')


def main():
    """Parse arguments and dispatch to the appropriate subcommand."""
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='subcommand')

    build_p = sub.add_parser('build', help='Build the documentation (default).')
    build_p.add_argument('--no-exec', action='store_true',
                         help='Skip notebook execution; use existing _executed_book/.')
    build_p.add_argument('--no-serial', action='store_true',
                         help='Skip execution of serial (non-MPI) notebooks.')
    build_p.add_argument('--no-mpi', action='store_true',
                         help='Skip execution of MPI notebooks.')
    build_p.add_argument('--fast', action='store_true',
                         help='Parallel Sphinx build (-j auto); skips warnings-as-errors.')
    build_p.add_argument('--workers', type=int, default=None,
                         help='Number of parallel workers (default: cpu_count).')

    sub.add_parser('clean', help='Remove all generated files.')

    args = parser.parse_args()

    if args.subcommand is None or args.subcommand == 'build':
        if args.subcommand is None:
            args.no_exec = False
            args.no_serial = False
            args.no_mpi = False
            args.fast = False
            args.workers = None
        cmd_build(args)
    elif args.subcommand == 'clean':
        cmd_clean(args)


if __name__ == '__main__':
    main()
