name: 'Setup OpenMDAO Pixi Environment'
description: 'Sets up Pixi with OpenMDAO environment'

inputs:
  environment:
    description: 'Pixi environment(s) to install'
    required: false
    default: 'py313'
  frozen:
    description: 'Use frozen lock file (recommended for CI)'
    required: false
    default: 'true'
  openmdao_install_from:
    description: 'How to install OpenMDAO: pypi, github, wheel, local, local_developer, or none'
    required: false
    default: 'pypi'
  openmdao_version:
    description: 'OpenMDAO version (for PyPI and Github installs only): "" (latest) or str (e.g. "3.42.0")'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Determine pixi.toml source
      shell: bash -l {0}
      run: |
        # Check if we're in the OpenMDAO repo
        if [[ "${{ github.repository }}" == "OpenMDAO/OpenMDAO" ]]; then
          echo "Running in OpenMDAO repo, using local pixi.toml"
          echo "PIXI_MANIFEST=pixi.toml" >> $GITHUB_ENV
        else
          echo "Running outside OpenMDAO repo, using pixi.toml from action checkout"
          # Action is at .github/actions/setup_openmdao_pixi/, so go up 3 levels to repo root
          echo "PIXI_MANIFEST=${{ github.action_path }}/../../../pixi.toml" >> $GITHUB_ENV
        fi

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        manifest-path: ${{ env.PIXI_MANIFEST }}
        environments: ${{ inputs.environment }}
        frozen: ${{ inputs.frozen }}
        cache: false

    - name: 'Install OpenMDAO'
      shell: bash -l {0}
      run: |
        eval "$(pixi shell-hook -e ${{ inputs.environment }})"
        echo "============================================================="
        echo "Install OpenMDAO"
        echo "============================================================="

        INSTALL_FROM="${{ inputs.openmdao_install_from }}"
        VERSION="${{ inputs.openmdao_version }}"

        case "$INSTALL_FROM" in
          pypi)
            if [[ -n "$VERSION" ]]; then
              echo "Installing OpenMDAO==$VERSION from PyPI"
              python -m pip install "openmdao==${VERSION}" --no-deps
            else
              echo "Installing latest OpenMDAO from PyPI"
              python -m pip install "openmdao" --no-deps
            fi
            ;;

          github)
            if [[ -n "$VERSION" ]]; then
              echo "Installing OpenMDAO@${VERSION} from GitHub"
              python -m pip install "git+https://github.com/OpenMDAO/OpenMDAO.git@${VERSION}#egg=openmdao" --no-deps
            else
              echo "Installing OpenMDAO@master from GitHub"
              python -m pip install "git+https://github.com/OpenMDAO/OpenMDAO.git@master#egg=openmdao" --no-deps
            fi
            ;;

          wheel)
            echo "Building wheel"
            pip wheel --no-deps .
            WHEEL=$(find openmdao-*.whl)
            echo "Installing from wheel: $WHEEL"
            python -m pip install "${WHEEL}" --no-deps
            ;;

          local_developer)
            echo "Installing from local directory in developer mode"
            python -m pip install -e . --no-deps
            ;;

          local)
            echo "Installing from local directory"
            python -m pip install . --no-deps
            ;;

          none|"")
            echo "Skipping OpenMDAO installation"
            ;;

          *)
            echo "Error: Unknown install method '$INSTALL_FROM'"
            exit 1
            ;;
        esac

    - name: Display installed packages
      shell: bash -l {0}
      run: |
        pixi list -e "${{ inputs.environment }}" --explicit
