name: OpenMDAO Tests (pixi)

on:
  # Trigger on push or pull request events for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Trigger on release, to publish release versioned docs to openmdao.org
  release:
    types: [published]

  # Allow running the workflow manually from the Actions tab
  # All jobs are included by default and may be deselected if desired
  workflow_dispatch:

    inputs:

      run_name:
        type: string
        description: 'Name of workflow run as it will appear under Actions tab:'
        required: false
        default: ""

      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  # Cancel any existing CI runs if we push to this branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name:  ${{ inputs.run_name }}

permissions: {}

jobs:

  tests:

    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-24.04, macos-latest]
        PIXI_ENVIRONMENT: [minimal, py311, py312, default, py314, dev]
        BANDIT: [false]
        RUFF: [false]
        SNOPT: [true]
        COVERAGE: [false]
        include:

          # Windows - default
          - OS: windows-latest
            PIXI_ENVIRONMENT: default
            BANDIT: false
            RUFF: false
            COVERAGE: default

          # Windows - minimal
          - OS: windows-latest
            PIXI_ENVIRONMENT: minimal
            BANDIT: false
            RUFF: false
            COVERAGE: false

          # Only test the oldest environment on ubuntu
          - OS: ubuntu-24.04
            PIXI_ENVIRONMENT: oldest
            BANDIT: false
            RUFF: false
            SNOPT: true
            COVERAGE: false

          # Bandit only on Ubuntu py312
          - OS: ubuntu-24.04
            PIXI_ENVIRONMENT: py312
            BANDIT: true
            RUFF: false
            COVERAGE: false

          # Do ruff and coverage on Ubuntu dev
          - OS: ubuntu-24.04
            PIXI_ENVIRONMENT: dev
            BANDIT: false
            RUFF: true
            COVERAGE: true

        exclude:
          # Exclude the duplicate ubuntu-24.04 + py312 with BANDIT: false
          - OS: ubuntu-24.04
            PIXI_ENVIRONMENT: py312
            BANDIT: false
            COVERAGE: false

          # Exclude the duplicate ubuntu-24.04 + dev with RUFF: false and COVERAGE: false
          - OS: ubuntu-24.04
            PIXI_ENVIRONMENT: dev
            BANDIT: false
            RUFF: false
            COVERAGE: false

    runs-on: ${{ matrix.OS }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run OpenMDAO Tests
        uses: ./.github/actions/run_openmdao_tests_pixi
        with:
          OS: ${{ matrix.OS }}
          PIXI_ENVIRONMENT: ${{ matrix.PIXI_ENVIRONMENT }}
          BANDIT: ${{ matrix.BANDIT }}
          RUFF: ${{ matrix.RUFF }}
          SNOPT: ${{ matrix.SNOPT }}
          COVERAGE: ${{ matrix.COVERAGE }}
          OPENMDAO_INSTALL_FROM: 'wheel'
          debug_enabled: ${{ inputs.debug_enabled || false }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          snopt_location_77: ${{ secrets.SNOPT_LOCATION_77 }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Signal to Coveralls that all parallel test jobs have completed.
  # See: https://docs.coveralls.io/parallel-builds
  coveralls:
    name: Finish Coveralls
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ always() }}
    continue-on-error: true
    steps:
      - name: Close parallel build on Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  related_tests:
    name: Run Dymos & pyCycle Tests
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Dymos Tests
        repo: ${{ github.repository_owner }}/dymos
        inputs: >
          {
            "run_name": "Test Latest OpenMDAO Development Version",
            "latest": true
           }
        token: ${{ secrets.ACCESS_TOKEN }}
      if: github.event_name == 'push'

    - uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: pyCycle Tests
        repo: ${{ github.repository_owner }}/pycycle
        inputs: >
          {
            "run_name": "Test Latest OpenMDAO Development Version",
            "Ubuntu_Baseline": false,
            "MacOS_Baseline": false,
            "Windows_Baseline": false,
            "OpenMDAO_Dev": true
           }
        token: ${{ secrets.ACCESS_TOKEN }}
      if: github.event_name == 'push'