# Run OpenMDAO tests against unfrozen (latest) pixi dependencies
name: OpenMDAO Latest (pixi)

on:

  # Run on the 1st and 15th of each month at 1:00 AM EST (06:00 UTC)
  schedule:
    - cron: '0 6 1,15 * *'

  # Allow running the workflow manually from the Actions tab
  workflow_dispatch:

    inputs:

      run_name:
        type: string
        description: 'Name of workflow run as it will appear under Actions tab:'
        required: false
        default: ""

      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

      openmdao_install_from:
        type: choice
        description: 'How to install OpenMDAO'
        required: false
        default: 'github'
        options:
          - github
          - pypi
          - wheel
          - local
          - local_developer
          - none

      frozen:
        type: boolean
        description: 'Use frozen pixi lock file (uncheck to update dependencies)'
        required: false
        default: false

concurrency:
  # Cancel any existing runs if we trigger the workflow again
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: ${{ inputs.run_name }}

permissions: {}

jobs:

  tests:

    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-24.04, macos-latest, windows-latest]
        PIXI_ENVIRONMENT: [default, dev, py314]
        BANDIT: [false]
        RUFF: [false]
        SNOPT: [true]
        COVERAGE: [false]

    runs-on: ${{ matrix.OS }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run OpenMDAO Tests
        uses: ./.github/actions/run_openmdao_tests_pixi
        with:
          OS: ${{ matrix.OS }}
          PIXI_ENVIRONMENT: ${{ matrix.PIXI_ENVIRONMENT }}
          BANDIT: ${{ matrix.BANDIT }}
          RUFF: ${{ matrix.RUFF }}
          SNOPT: ${{ matrix.SNOPT }}
          COVERAGE: ${{ matrix.COVERAGE }}
          OPENMDAO_INSTALL_FROM: ${{ inputs.openmdao_install_from || 'github' }}
          frozen: ${{ inputs.frozen || false }}
          debug_enabled: ${{ inputs.debug_enabled || false }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          snopt_location_77: ${{ secrets.SNOPT_LOCATION_77 }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
