name: Update status of associated POEM

on:
  pull_request_target:
    types:
      - closed

jobs:

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Display run details
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Triggered by: ${GITHUB_EVENT_NAME}"
          echo "Initiated by: ${GITHUB_ACTOR}"
          echo "============================================================="


      - name: Update POEM
        id: update_poem
        env:
          BODY: ${{ github.event.pull_request.body }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "BODY:\n$BODY"
          echo "----------------------"

          while IFS= read -r line; do
            ISSUE_ID=$(echo $line | grep "Resolves #" -)
            if [[ "$ISSUE_ID" ]]; then
              ISSUE_ID=$(echo $ISSUE_ID | cut -d '#' -f 2)
              break
            fi
          done <<< "$BODY"

          echo "ISSUE: $ISSUE_ID"

          echo "----------------------"

          ISSUE_TEXT=`gh --repo OpenMDAO/OpenMDAO issue view $ISSUE_ID`

          echo "ISSUE TEXT:"
          echo $ISSUE_TEXT

          echo "----------------------"

          ASSOCIATED_POEM=""
          POEM_ID=""

          while IFS= read -r line; do
            if [[ "$ASSOCIATED_POEM" ]]; then
              POEM_ID=$(echo $line)
              if [[ "$POEM_ID" ]]; then
                break
              fi
            else
              ASSOCIATED_POEM=$(echo $line | grep "Associated POEM" -)
            fi
          done <<< "$ISSUE_TEXT"

          echo "POEM_ID: $POEM_ID"

          echo "----------------------"

          echo "POEM_ID=$POEM_ID" >> $GITHUB_OUTPUT

      - name: Update POEM status to Integrated
        if: steps.update_poem.outputs.POEM_ID != ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: ${{ github.repository_owner }}/POEMs
          workflow: Update POEM status to Integrated
          inputs: '{ "poem_integrated": "${{ steps.update_poem.outputs.POEM_ID }}" }'
          token: ${{ secrets.ACCESS_TOKEN }}
